project_id = "aanuxmipcjiqcmlqfdjk"

[functions.generate-career-recommendations]
verify_jwt = false

[functions.generate-career-description]
verify_jwt = false

[functions.map-opportunities]
verify_jwt = false

[functions.train-recommendation-model]
verify_jwt = true

[functions.generate-quiz-questions]
verify_jwt = false

[functions.refresh-data]
verify_jwt = false